package com.staff.travel.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Merchant")
public class Merchant implements Serializable {
    @DynamoDBHashKey(attributeName = "MerchantId")
    @DynamoDBAutoGeneratedKey
    private String merchantId;

    @DynamoDBAttribute
    private String merchantName;

    @DynamoDBAttribute
    private int age;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private Address address;
}
